name: Deploy Discord Bot

on:
  push:
    branches:
      - clean-version

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: 192.241.155.120 
          username: root
          password: LEwJ7g:rR6-n7PH
          port: 22
          script: |
            cd "${{ github.repository }}"
            git pull origin main
            python Bot.py